export const questionData = [
  {
    id: 1,
    question: "Q1 Australia is a country as well as a continent.",
    correct: "True",
    answer: "",
    option: ["True", "False"],
    type: "True-False",
  },
  {
    id: 2,
    question: "Q2 What is national Animal of india?",
    correct: "lion",
    answer: "",
    option: [""],
    type: "Fill-in-the-black",
  },
  {
    id: 3,
    question: "Q3 Choose all Fruits",
    correct: "1",
    answer: "",
    option: ["Mangoes", "Apple", "Patato", "Car"],
    correct2: ["Mangoes", "Apple", "", ""],
    answer2: ["", "", "", ""],
    type: "MultiCorrect",
  },
  {
    id: 4,
    question: "Q4 How many days in a week",
    correct: "7",
    answer: "",
    option: ["6", "4", "7", "8"],
    type: "multiple-choise",
  },
  {
    id: 5,
    correct: "1",
    answer: "",
    question: "Q5 match the following",
    correct2: ["fruit", "vehicle", "animal"],
    option: ["animal", "fruit", "vehicle"],
    answer2: ["", "", ""],
    type: "match-the-following",
  },
];
